### PR TITLE
Fix #238: Non converging operations with unordered deletes. Migration to fix existing datastores.

### LINKED ISSUE #238: Non-Converging Operations
Hi,

I'm currently working on a [JS port](https://github.com/dozyio/js-ds-crdt) and encountered an edge case during interop testing where the values do not converge as expected, despite the DAGs being identical.

When performing a sequence of `put`, `put`, `delete` operations on replica0, and a single `put` on replica1 (all on the same key), replica0 reverts to the second `put` operation, while replica1 retains its initial `put`. This causes the replicas to hold different values even though their DAGs are the same.

Any ideas?

Test case below

```go
func TestCRDTPutPutDelete(t *testing.T) {
	replicas, closeReplicas := makeNReplicas(t, 2, nil)
	defer closeReplicas()

	br0 := replicas[0].broadcaster.(*mockBroadcaster)
	br0.dropProb = 101

	br1 := replicas[1].broadcaster.(*mockBroadcaster)
	br1.dropProb = 101

	k := ds.NewKey("k1")

	// r0 - put put delete
	err := replicas[0].Put(context.Background(), k, []byte("r0-1"))
	if err != nil {
		t.Fatal(err)
	}
	err = replicas[0].Put(context.Background(), k, []byte("r0-2"))
	if err != nil {
		t.Fatal(err)
	}
	err = replicas[0].Delete(context.Background(), k)
	if err != nil {
		t.Fatal(err)
	}

	// r1 - put
	err = replicas[1].Put(context.Background(), k, []byte("r1-1"))
	if err != nil {
		t.Fatal(err)
	}

	br0.dropProb = 0
	br1.dropProb = 0

	time.Sleep(15 * time.Second)

	r0Res, err := replicas[0].Get(context.Background(), ds.NewKey("k1"))
	if err != nil {
		if !errors.Is(err, ds.ErrNotFound) {
			t.Fatal(err)
		}
	}

	r1Res, err := replicas[1].Get(context.Background(), ds.NewKey("k1"))
	if err != nil {
		t.Fatal(err)
	}

	fmt.Printf("r0Res: %s\nr1Res: %s\n", string(r0Res), string(r1Res))
	if string(r0Res) != string(r1Res) {
		t.Log("r0 dag")
		replicas[0].PrintDAG()

		t.Log("r1 dag")
		replicas[1].PrintDAG()

		t.Fatal("r0 and r1 should have the same value")
	}
}
```

```sh
go test -test.count 1 -v -run TestCRDTPutPutDelete ./...
?   	github.com/ipfs/go-ds-crdt/pb	[no test files]
=== RUN   TestCRDTPutPutDelete
r0Res: r0-2
r1Res: r1-1
    crdt_test.go:536: r0 dag
- 1 | x3nq: Add: {/k1:r1-1,}. Rmv: {}. Links: {}:
- 3 | rn6q: Add: {}. Rmv: {/k1,/k1,}. Links: {obqq,}:
 - 2 | obqq: Add: {/k1:r0-2,}. Rmv: {}. Links: {43z4,}:
  - 1 | 43z4: Add: {/k1:r0-1,}. Rmv: {}. Links: {}:
    crdt_test.go:539: r1 dag
- 1 | x3nq: Add: {/k1:r1-1,}. Rmv: {}. Links: {}:
- 3 | rn6q: Add: {}. Rmv: {/k1,/k1,}. Links: {obqq,}:
 - 2 | obqq: Add: {/k1:r0-2,}. Rmv: {}. Links: {43z4,}:
  - 1 | 43z4: Add: {/k1:r0-1,}. Rmv: {}. Links: {}:
    crdt_test.go:542: r0 and r1 should have the same value
--- FAIL: TestCRDTPutPutDelete (30.00s)
```

### PR DESCRIPTION
**Pull request by hsanjuan**
This is made of two commits, one fixes the problem with the wrong values being set for elements that are partially tombstoned. The second adds a migration to fix potentially wrong values, but also to ensure that we return the right thing now that we don't check for tombstoning anymore on Get(). Fixes #238 .

### CODE REVIEW

**Comment by hsanjuan** [comment]
@dozyio I wonder if you are able to have a look

**Comment by dozyio** [comment]
Being playing around a bit with this PR and it seems good! Puts and deletes converging as expected.

Tested the migrations a little bit and seems ok

File: set.go [hunk 1]
```diff
@@ -477,7 +337,7 @@ func (s *set) setPriority(ctx context.Context, writeStore ds.Write, key string,
 // value is lexicographically higher than the current value.
 func (s *set) setValue(ctx context.Context, writeStore ds.Write, key, id string, value []byte, prio uint64) error {
 	// If this key was tombstoned already, do not store/update the value
-	// at all.
+	// at
```
Comment (dozyio) [inline set.go:340]: missing word / delete this line?

**Review by dozyio — APPROVED** [review]

File: set.go [hunk 2]
```diff
@@ -518,6 +377,113 @@ func (s *set) setValue(ctx context.Context, writeStore ds.Write, key, id string,
...
+		}
+	}
+
+	// if deltaCid.Defined() {
+	// 	cidStr := deltaCid.String()
+	// 	cidStr = cidStr[len(cidStr)-4:]
+	// 	fmt.Printf("best value: (%s, %d) on block: %s\n", bestValue, bestPriority, cidStr)
+	// } else {
+	// 	fmt.Printf("best value: NONE\n")
+	// }
```
Comment (hsanjuan) [inline set.go:483]: remove

**Comment by hsanjuan** [comment]
Thanks very much @dozyio for the review and for finding the bug!
